// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	models "computer-club/internal/models"
	context "context"

	mock "github.com/stretchr/testify/mock"

	repository "computer-club/internal/repository"
)

// ComputerRepository is an autogenerated mock type for the ComputerRepository type
type ComputerRepository struct {
	mock.Mock
}

// AddComputer provides a mock function with given fields: ctx
func (_m *ComputerRepository) AddComputer(ctx context.Context) (*models.Computer, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for AddComputer")
	}

	var r0 *models.Computer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*models.Computer, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *models.Computer); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Computer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ChangeComputerStatus provides a mock function with given fields: ctx, tx, computer, status
func (_m *ComputerRepository) ChangeComputerStatus(ctx context.Context, tx repository.Transaction, computer *models.Computer, status string) error {
	ret := _m.Called(ctx, tx, computer, status)

	if len(ret) == 0 {
		panic("no return value specified for ChangeComputerStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.Transaction, *models.Computer, string) error); ok {
		r0 = rf(ctx, tx, computer, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteComputer provides a mock function with given fields: ctx, computer
func (_m *ComputerRepository) DeleteComputer(ctx context.Context, computer *models.Computer) error {
	ret := _m.Called(ctx, computer)

	if len(ret) == 0 {
		panic("no return value specified for DeleteComputer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Computer) error); ok {
		r0 = rf(ctx, computer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetComputerByID provides a mock function with given fields: ctx, id
func (_m *ComputerRepository) GetComputerByID(ctx context.Context, id int) (*models.Computer, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetComputerByID")
	}

	var r0 *models.Computer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*models.Computer, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *models.Computer); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Computer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetComputers provides a mock function with given fields: ctx
func (_m *ComputerRepository) GetComputers(ctx context.Context) ([]*models.Computer, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetComputers")
	}

	var r0 []*models.Computer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*models.Computer, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*models.Computer); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Computer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewComputerRepository creates a new instance of ComputerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewComputerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ComputerRepository {
	mock := &ComputerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
