// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	models "computer-club/internal/models"
	context "context"

	mock "github.com/stretchr/testify/mock"

	repository "computer-club/internal/repository"
)

// SessionRepository is an autogenerated mock type for the SessionRepository type
type SessionRepository struct {
	mock.Mock
}

// BeginTransaction provides a mock function with given fields: ctx
func (_m *SessionRepository) BeginTransaction(ctx context.Context) repository.Transaction {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for BeginTransaction")
	}

	var r0 repository.Transaction
	if rf, ok := ret.Get(0).(func(context.Context) repository.Transaction); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.Transaction)
		}
	}

	return r0
}

// CacheSession provides a mock function with given fields: ctx, session
func (_m *SessionRepository) CacheSession(ctx context.Context, session *models.Session) error {
	ret := _m.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for CacheSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Session) error); ok {
		r0 = rf(ctx, session)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CheckStatus provides a mock function with given fields: session, status
func (_m *SessionRepository) CheckStatus(session models.Session, status string) error {
	ret := _m.Called(session, status)

	if len(ret) == 0 {
		panic("no return value specified for CheckStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(models.Session, string) error); ok {
		r0 = rf(session, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateSession provides a mock function with given fields: ctx, tx, userID, pcNumber, tariff
func (_m *SessionRepository) CreateSession(ctx context.Context, tx repository.Transaction, userID int64, pcNumber int, tariff *models.Tariff) (*models.Session, error) {
	ret := _m.Called(ctx, tx, userID, pcNumber, tariff)

	if len(ret) == 0 {
		panic("no return value specified for CreateSession")
	}

	var r0 *models.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.Transaction, int64, int, *models.Tariff) (*models.Session, error)); ok {
		return rf(ctx, tx, userID, pcNumber, tariff)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.Transaction, int64, int, *models.Tariff) *models.Session); ok {
		r0 = rf(ctx, tx, userID, pcNumber, tariff)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.Transaction, int64, int, *models.Tariff) error); ok {
		r1 = rf(ctx, tx, userID, pcNumber, tariff)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteSessionCache provides a mock function with given fields: ctx, id
func (_m *SessionRepository) DeleteSessionCache(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSessionCache")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetActiveSessions provides a mock function with given fields: ctx
func (_m *SessionRepository) GetActiveSessions(ctx context.Context) []*models.Session {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveSessions")
	}

	var r0 []*models.Session
	if rf, ok := ret.Get(0).(func(context.Context) []*models.Session); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Session)
		}
	}

	return r0
}

// GetSessionByID provides a mock function with given fields: ctx, tx, sessionID
func (_m *SessionRepository) GetSessionByID(ctx context.Context, tx repository.Transaction, sessionID int64) (*models.Session, error) {
	ret := _m.Called(ctx, tx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for GetSessionByID")
	}

	var r0 *models.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.Transaction, int64) (*models.Session, error)); ok {
		return rf(ctx, tx, sessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.Transaction, int64) *models.Session); ok {
		r0 = rf(ctx, tx, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.Transaction, int64) error); ok {
		r1 = rf(ctx, tx, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HasActiveSession provides a mock function with given fields: ctx, tx, userID
func (_m *SessionRepository) HasActiveSession(ctx context.Context, tx repository.Transaction, userID int64) (bool, error) {
	ret := _m.Called(ctx, tx, userID)

	if len(ret) == 0 {
		panic("no return value specified for HasActiveSession")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.Transaction, int64) (bool, error)); ok {
		return rf(ctx, tx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.Transaction, int64) bool); ok {
		r0 = rf(ctx, tx, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.Transaction, int64) error); ok {
		r1 = rf(ctx, tx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarkSessionFinished provides a mock function with given fields: ctx, tx, sessionID
func (_m *SessionRepository) MarkSessionFinished(ctx context.Context, tx repository.Transaction, sessionID int64) error {
	ret := _m.Called(ctx, tx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for MarkSessionFinished")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.Transaction, int64) error); ok {
		r0 = rf(ctx, tx, sessionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSessionRepository creates a new instance of SessionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSessionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SessionRepository {
	mock := &SessionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
