// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	models "computer-club/internal/models"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// TariffRepository is an autogenerated mock type for the TariffRepository type
type TariffRepository struct {
	mock.Mock
}

// GetTariff provides a mock function with given fields: ctx
func (_m *TariffRepository) GetTariff(ctx context.Context) ([]models.Tariff, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetTariff")
	}

	var r0 []models.Tariff
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.Tariff, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.Tariff); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Tariff)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTariffByID provides a mock function with given fields: ctx, id
func (_m *TariffRepository) GetTariffByID(ctx context.Context, id int64) (*models.Tariff, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetTariffByID")
	}

	var r0 *models.Tariff
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*models.Tariff, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *models.Tariff); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Tariff)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTariffRepository creates a new instance of TariffRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTariffRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TariffRepository {
	mock := &TariffRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
