// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	models "computer-club/internal/models"
	context "context"

	mock "github.com/stretchr/testify/mock"

	repository "computer-club/internal/repository"
)

// WalletRepository is an autogenerated mock type for the WalletRepository type
type WalletRepository struct {
	mock.Mock
}

// BeginTransaction provides a mock function with given fields: ctx
func (_m *WalletRepository) BeginTransaction(ctx context.Context) repository.Transaction {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for BeginTransaction")
	}

	var r0 repository.Transaction
	if rf, ok := ret.Get(0).(func(context.Context) repository.Transaction); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.Transaction)
		}
	}

	return r0
}

// CreateTransaction provides a mock function with given fields: ctx, tx, userID, amount, typ, tariff
func (_m *WalletRepository) CreateTransaction(ctx context.Context, tx repository.Transaction, userID int64, amount float64, typ string, tariff *models.Tariff) (*models.Transaction, error) {
	ret := _m.Called(ctx, tx, userID, amount, typ, tariff)

	if len(ret) == 0 {
		panic("no return value specified for CreateTransaction")
	}

	var r0 *models.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.Transaction, int64, float64, string, *models.Tariff) (*models.Transaction, error)); ok {
		return rf(ctx, tx, userID, amount, typ, tariff)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.Transaction, int64, float64, string, *models.Tariff) *models.Transaction); ok {
		r0 = rf(ctx, tx, userID, amount, typ, tariff)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.Transaction, int64, float64, string, *models.Tariff) error); ok {
		r1 = rf(ctx, tx, userID, amount, typ, tariff)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateWallet provides a mock function with given fields: ctx, tx, wallet
func (_m *WalletRepository) CreateWallet(ctx context.Context, tx repository.Transaction, wallet *models.Wallet) error {
	ret := _m.Called(ctx, tx, wallet)

	if len(ret) == 0 {
		panic("no return value specified for CreateWallet")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.Transaction, *models.Wallet) error); ok {
		r0 = rf(ctx, tx, wallet)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Deposit provides a mock function with given fields: ctx, tx, userID, amount
func (_m *WalletRepository) Deposit(ctx context.Context, tx repository.Transaction, userID int64, amount float64) error {
	ret := _m.Called(ctx, tx, userID, amount)

	if len(ret) == 0 {
		panic("no return value specified for Deposit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.Transaction, int64, float64) error); ok {
		r0 = rf(ctx, tx, userID, amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetBalance provides a mock function with given fields: ctx, userID
func (_m *WalletRepository) GetBalance(ctx context.Context, userID int64) (float64, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetBalance")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (float64, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) float64); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTransactions provides a mock function with given fields: ctx, userID
func (_m *WalletRepository) GetTransactions(ctx context.Context, userID int64) ([]*models.Transaction, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactions")
	}

	var r0 []*models.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]*models.Transaction, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []*models.Transaction); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Withdraw provides a mock function with given fields: ctx, tx, userID, amount
func (_m *WalletRepository) Withdraw(ctx context.Context, tx repository.Transaction, userID int64, amount float64) error {
	ret := _m.Called(ctx, tx, userID, amount)

	if len(ret) == 0 {
		panic("no return value specified for Withdraw")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.Transaction, int64, float64) error); ok {
		r0 = rf(ctx, tx, userID, amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewWalletRepository creates a new instance of WalletRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWalletRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *WalletRepository {
	mock := &WalletRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
