apiVersion: v1
kind: Secret
metadata:
  name: club-service-secret
  namespace: computer-club
type: Opaque
data:
  DB_USER: YWRtaW4=  # base64 encoded "admin"
  DB_PASSWORD: c2VjcmV0  # base64 encoded "secret"
  JWT_SECRET: ZGZnaGRmZ3lkaGRkaDY1NnkydXJ0aHJ0aGox  # base64 encoded "dfghdfgydhdh656y5yrthrthj"
