// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Проверяет email и пароль, возвращает JWT-токен",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Авторизация пользователя",
                "parameters": [
                    {
                        "description": "Данные для входа",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешный вход",
                        "schema": {
                            "$ref": "#/definitions/handlers.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Некорректный запрос (невалидный JSON)",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Ошибка авторизации - неверный email или пароль",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Создает нового пользователя с указанными данными",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Регистрация пользователя",
                "parameters": [
                    {
                        "description": "Данные для регистрации",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.RegisterUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Пользователь успешно зарегистрирован",
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    },
                    "400": {
                        "description": "Некорректные данные (пустое имя, email, короткий пароль, неверная роль)",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "Пользователь уже существует",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/computers": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает список всех компьютеров и их статусы (доступно только для администраторов)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "computers"
                ],
                "summary": "Получение статуса компьютеров",
                "responses": {
                    "200": {
                        "description": "Успешный ответ",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Computer"
                            }
                        }
                    },
                    "403": {
                        "description": "Ошибка доступа - недостаточно прав",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Добавляет компьютер в базу данных (доступно только для администраторов)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "computers"
                ],
                "summary": "Добавляет компьютер",
                "responses": {
                    "200": {
                        "description": ": \"Компьютер успешно добавлен",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Ошибка доступа - недостаточно прав",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/computers/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Удаляет компьютер из базы данных (доступно только для администраторов)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "computers"
                ],
                "summary": "Удаляет компьютер",
                "responses": {
                    "200": {
                        "description": ": \"Компьютер успешно удален",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Некорректный ID компьютера",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Ошибка доступа - недостаточно прав",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Компьютер не найден",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "Компьютер занят",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/pay": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Администратор пополняет счет указанного пользователя (admin only)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wallet"
                ],
                "summary": "Пополнение счета игрока",
                "parameters": [
                    {
                        "description": "Данные для пополнения счета",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.PutMoneyReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Счет успешно пополнен",
                        "schema": {
                            "$ref": "#/definitions/models.Transaction"
                        }
                    },
                    "400": {
                        "description": "Некорректный запрос (например, сумма ≤ 0)",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Ошибка доступа - недостаточно прав",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Пользователь не найден",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/session/active": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает список всех активных сессий (только для администраторов)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "Получение активных сессий",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Session"
                            }
                        }
                    },
                    "403": {
                        "description": "ошибка доступа к текущему запросу. необходима роль пользователя: админ",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/session/end": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Завершает активную сессию по её идентификатору",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "Завершение сессии",
                "parameters": [
                    {
                        "description": "Данные для завершения сессии",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.EndSessionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "message\": \"Session ended successfully",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Некорректный запрос (например, session_id == 0)",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Сессия или компьютер не найдены",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "Сессия уже завершена или компьютер уже свободный",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера при закрытии сессии или транзакции базы данных или редис не удалил данные",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/session/start": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Запускает новую сессию для пользователя на указанном ПК с выбранным тарифом",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "Начало сессии",
                "parameters": [
                    {
                        "description": "Данные для старта сессии",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.StartSessionReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Session"
                        }
                    },
                    "400": {
                        "description": "ошибка JSON запроса",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "неправильный user_id в токене",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Не найдено - user, computer или tariff или кошелек",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "Сессия уже активная или компьютер занят",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "внутренняя проблема поиска в базе данных или ошибка сохранения изменения транзакции базы данных или редис не создал данные",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/tariff": {
            "get": {
                "description": "Возвращает список всех доступных тарифов",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tariffs"
                ],
                "summary": "Получение списка тарифов",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Tariff"
                            }
                        }
                    },
                    "500": {
                        "description": "ошибка при поиске тарифов в базе данных",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Создает новый тариф с указанными данными (доступен для администратора)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tariffs"
                ],
                "summary": "Создание нового тарифа",
                "parameters": [
                    {
                        "description": "Данные для тарифа",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.TariffBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Тариф успешно создан",
                        "schema": {
                            "$ref": "#/definitions/models.Tariff"
                        }
                    },
                    "400": {
                        "description": "Некорректные данные (пустое имя, отрицательный айди или цена или длительность)",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Недостаточно прав: нужен пользователь с ролью админ",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "Айди тарифа уже используется",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/tariff/{id}": {
            "get": {
                "description": "Возвращает информацию о тарифе по указанному ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tariffs"
                ],
                "summary": "Получение тарифа по ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID тарифа",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Tariff"
                        }
                    },
                    "400": {
                        "description": "ошибка чтения тариф id",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "тариф не найден",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "удаление Тарифа из базы данных (доступно для админа)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tariffs"
                ],
                "summary": "удаление Тарифа",
                "responses": {
                    "200": {
                        "description": ": \"тариф успешно удален",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Некорректный ID тарифа",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Ошибка доступа - недостаточно прав",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Тариф не найден",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Получение списка пользователей (может только админ)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Получение списка пользователей",
                "responses": {
                    "200": {
                        "description": "Список пользователей успешно показан",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.User"
                            }
                        }
                    },
                    "403": {
                        "description": "Недостаточно прав",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Список пользователей пуст",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users/info": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает информацию о пользователе, баланс и транзакции",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Получение информации о пользователе",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.UserInfoResponse"
                        }
                    },
                    "400": {
                        "description": "Некорректный user_id",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Кошелек не найден или пользователь",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Получение пользователя по ID (может только админ)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Получение пользователя по ID",
                "responses": {
                    "200": {
                        "description": "Пользователь успешно показан",
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    },
                    "400": {
                        "description": "Некорректный id",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Недостаточно прав",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Пользователь не найден",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.EndSessionRequest": {
            "type": "object",
            "properties": {
                "session_id": {
                    "type": "integer",
                    "example": 123
                }
            }
        },
        "handlers.LoginRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "password": {
                    "type": "string",
                    "example": "secret"
                }
            }
        },
        "handlers.LoginResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                }
            }
        },
        "handlers.PutMoneyReq": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "handlers.RegisterUserRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "ivan@example.com"
                },
                "password": {
                    "type": "string",
                    "example": "secret123"
                },
                "role": {
                    "type": "string",
                    "example": "customer"
                }
            }
        },
        "handlers.StartSessionReq": {
            "type": "object",
            "properties": {
                "pc_number": {
                    "type": "integer"
                },
                "tariff_id": {
                    "type": "integer"
                }
            }
        },
        "handlers.TariffBody": {
            "type": "object",
            "properties": {
                "duration": {
                    "type": "integer",
                    "example": 10
                },
                "name": {
                    "type": "string",
                    "example": "Free"
                },
                "price": {
                    "type": "number",
                    "example": 0
                },
                "tariff_id": {
                    "type": "integer",
                    "example": 123
                }
            }
        },
        "handlers.UserInfoResponse": {
            "type": "object",
            "properties": {
                "balance": {
                    "type": "number",
                    "example": 100.5
                },
                "transactions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Transaction"
                    }
                },
                "user": {
                    "$ref": "#/definitions/models.User"
                }
            }
        },
        "models.Computer": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "pc_number": {
                    "type": "integer"
                },
                "status": {
                    "$ref": "#/definitions/models.ComputerStatus"
                }
            }
        },
        "models.ComputerStatus": {
            "type": "string",
            "enum": [
                "free",
                "busy"
            ],
            "x-enum-varnames": [
                "Free",
                "Busy"
            ]
        },
        "models.Session": {
            "type": "object",
            "properties": {
                "end_time": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "pc_number": {
                    "type": "integer"
                },
                "start_time": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/models.SessionStatus"
                },
                "tariff_id": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "models.SessionStatus": {
            "type": "string",
            "enum": [
                "active",
                "finished"
            ],
            "x-enum-varnames": [
                "Active",
                "Finished"
            ]
        },
        "models.Tariff": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "duration": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                }
            }
        },
        "models.Transaction": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "tariff_id": {
                    "type": "integer"
                },
                "type": {
                    "$ref": "#/definitions/models.TransactionType"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "models.TransactionType": {
            "type": "string",
            "enum": [
                "add",
                "buy"
            ],
            "x-enum-varnames": [
                "Add",
                "Buy"
            ]
        },
        "models.User": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "API Computer-club",
	Description:      "This is a sample API with Swagger",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
